server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-migration-target
  temporal:
    workers:
      - task-queue: default
        workflow-classes:
          - io.temporal.examples.backend.MigratedWorkflowImpl
        activity-beans:
          - migration-support
    namespace: migration-demo.sdvdw # https://docs.temporal.io/cloud/#temporal-cloud-namespace-id
    connection:
      target: migration-demo.sdvdw.tmprl.cloud:7233
      mtls:
        key-file: /Users/mnichols/certs/migration-demo.sdvdw.key
        cert-chain-file: /Users/mnichols/certs/migration-demo.sdvdw.pem
  migration:
    state-query-name: 'getMigrationState'
    migration-signal-name: 'migrateIt'
    target:
      namespace: migration-demo.sdvdw
      connection:
        target: migration-demo.sdvdw.tmprl.cloud:7233
        mtls:
          key-file: /Users/mnichols/certs/migration-demo.sdvdw.key
          cert-chain-file: /Users/mnichols/certs/migration-demo.sdvdw.pem