server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-migration
  temporal:
    workersAutoDiscovery:
      packages: io.temporal.examples.backend
    connection:
      target: 127.0.0.1:7233
      target.namespace: default
  migration:
    state-query-name: 'getMigrationState'
