server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-migration
  temporal:
    workersAutoDiscovery:
      packages: io.temporal.examples
    namespace: migration-demo.sdvdw # https://docs.temporal.io/cloud/#temporal-cloud-namespace-id
    connection:
      target: migration-demo.sdvdw.tmprl.cloud:7233
      mtls:
        key-file: /Users/mnichols/certs/migration-demo.sdvdw.key
        cert-chain-file: /Users/mnichols/certs/migration-demo.sdvdw.pem

# (Note following configuration are not set by default but serve more as reference)
#    workers:
#      - task-queue: DemoTaskQueue
#        capacity:
#          max-concurrent-workflow-task-pollers: 6
#          max-concurrent-activity-task-pollers: 6
#        rate-limits:
#          max-worker-activities-per-second: 3
#          max-task-queue-activities-per-second: 3
#    workflow-cache:
#      max-instances: 10
#      max-threads: 10
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
